### ISSUE TITLE
X96 fixed point decimal type

### ISSUE THREAD

**Issue by mconcat** [gnoswap-labs/gnoswap#164]
I think the suffix `X96` is meaningful because it tells us the bigint is actually a 96-bit fixed point integers, but I agree that they should not appear in the variable names. A better way would be defining a new X96 wrapper type so we can enforce the decimal computation at the type level. Once we adapt u256 types we can also work on it.

_Originally posted by @mconcat in https://github.com/gnoswap-labs/gnoswap/pull/160#discussion_r1489358357_

**Comment by r3v4s** [comment]
if swap only uses Q96 notation, I do agree making wrapper.
BUT, if my memory serves me right swap uses not only x96, but x128 too.

After we finish all of refactor stuff, if swap uses only few(I think up to two) Qx notations we can make wrapper, larger than that.... it might be to lead us too many wrapper being exist
