### ISSUE TITLE
change contract path

### ISSUE THREAD

**Issue by r3v4s** [gnoswap-labs/gnoswap#165]
Very early version of gnoswap was deployed to package path `gno.land/r/~~`, for now we use `gno.land/r/demo/~~~`

I think we need its own path 
1. `gno.land/r/swap`
2. `gno.land/r/gnoswap`

leave anything in comments for alternatives @notJoon @mconcat

**Comment by notJoon** [comment]
I agree. However, `~/swap` seems ambiguous, so the `~/gnoswap` looks better

**Comment by mconcat** [comment]
👍 for `gno.land/r/gnoswap`
