### ISSUE TITLE
Consolidate `requireXXX` Panic Functions into a Single `require` Package

### ISSUE THREAD

**Issue by notJoon** [gnoswap-labs/gnoswap#167]
## Description

The current implementation has the `requireXXX` functions located within `./utils` in each directories. I think it would be nice if we consolidating them into a single package, like `require`.

This would also allow us to organize the existing functions (e.g. `requireUnsigned`, `requirePositive`) into a naming convention that aligns more closely with Go's recommended practices, like `require.XXX` format.

### List of possible methods

| name | description | use case |
|---|---|---|
| `Expect` (or `Must`) | Takes a condition as an parameter and checks if the result is true. | SwapRoute |
| `Equal` ( or, `Eq` / `MustEq`) |  Verifies that the two values are equal. | DrySwapRoute |
| `Positive` | Takes in a single value and determines if it is greater than zero. | bit_math |
| `Unsigned` | Takes in a single value and checks if it is greater than or equal to zero. | Mint |
| `PrevRealmPath` | Check the input path is the same value of `PrevRealmPath()`. |  Burn |

--- 
https://go.dev/blog/package-names

**Comment by r3v4s** [comment]
We can replace `Unsigned`, `Positive` in `uint256` package I think

**Comment by notJoon** [comment]
> We can replace `Unsigned`, `Positive` in `uint256` package I think

Definitely the uint256 is important

**Comment by r3v4s** [comment]
Just come to mind, a lot of testcase in [gnoswap](https://github.com/gnoswap-labs/gnoswap/blob/b32c233040e27b05cd7708ff5262dda966be13a0/pool/_TEST_INIT_basic_test.gno#L49-L53) or [gno](https://github.com/gnolang/gno/blob/ee0880b55b7f8bd51cd772106641801bfd44c9c5/docs/assets/how-to-guides/porting-solidity-to-gno/porting-1.gno#L1-L7) has helper function called `shouldXXX`


`requireEqual` and `shouldEQ` does exactly same thing except `shouldEQ` is only for test case(which takes *testing.T as first parameter)


I can't think of any advantages dividing these helpers, WDYT?

**Comment by r3v4s** [comment]
Since `require` is left over from solidity's require.
We've decided to remove it and just use if ~ panic
- https://github.com/gnoswap-labs/gnoswap/pull/189
